### ISSUE TITLE
MathCat stops working when the language is changed

### ISSUE THREAD

**Issue by brunoprietog** [NSoiffer/MathCAT#146]
I don't quite understand what is going on, but this is how I can reproduce it. Open Microsoft Edge, go to a page that has math on it and read it with MathCat. Then, change the language of MathCat and try to read the same formula. Now it won't read anything until you restart Microsoft Edge and NVDA.

**Comment by NSoiffer** [comment]
Can you repeat what you did and include/copy here any info in the NVDA log (its under NVDA's Tools preferences).  Thanks.

**Comment by NSoiffer** [comment]
I am unable to reproduce this although I sometimes need to restart NVDA to get the language change to happen.

@brunoprietog: 
* Did you change the language in the MathCAT preferences or in the NVDA Settings:Speech preference?
* What synthesizer are you using?
* What voice are you using?

Also, including the NVDA log would very helpful.

**Comment by brunoprietog** [comment]
I've looked into this in more detail, here are the steps:

1. With NVDA running, Open Microsoft Edge and navigate to a page that has math on it, the Mathcat documentation for example.
2. Read the expression under the level 2 heading "Why MathCAT?". You'll notice that everything works fine.
3. Change the language of MathCat to English.
4. Read the same expression again, you'll notice that it still reads in English.
5. Restart NVDA to test if that helps and read the expression again, you'll notice that it doesn't read anything.
6. Restart Microsoft Edge, open the same page to read the expression and you'll notice that it now reads it in Spanish.

Here are the logs of both runs of NVDA:

- [Mathcat nvda-old.txt](https://github.com/NSoiffer/MathCAT/files/12343859/Mathcat.nvda-old.txt)
- [Mathcat nvda.txt](https://github.com/NSoiffer/MathCAT/files/12343862/Mathcat.nvda.txt)

So, my conclusion is that changing the language of MathCat requires a restart of NVDA, I don't think  that is a problem if the user is informed. However, every time NVDA is executed, if Microsoft Edge is already open, NVDA doesn't read any math expressions. Microsoft Edge needs to be opened with NVDA running for it to recognize them. If for any reason you restart NVDA with Microsoft Edge open, NVDA will fail to read math and you'll have to restart Microsoft Edge again. Perhaps this is an NVDA problem and not a MathCat problem.

Let me know if this helps or if you can reproduce it, thanks!

**Comment by NSoiffer** [comment]
Thanks for the logs. I do see Edge complaining, but no error from calls to MathCAT.

Last week, I released MathCAT 0.3.6. Coincidentally, I redid the way MathCAT detects changes. It fixes a bug with noticing that the language changed, so that probably fixed the problem you are seeing. The new version is in the addon store. Please let me know if you still see a problem.

**Comment by brunoprietog** [comment]
Yes, now the language change works instantly. However, if you restart NVDA with Microsoft Edge open, absolutely nothing is read. Microsoft Edge needs to be opened with NDA started. If any NVDA restart occurs, it will stop reading math until you restart Microsoft Edge. I don't know if this is a NVDA error

**Comment by andrew-l-d** [comment]
I have occasionally noticed such behaviour with NVDA, not limited to browsers.  Usually alt-tabbing away and back again fixes it.  I doubt that it will often be a problem, as most screenreader users will not be launching a browser without NVDA running.

**Comment by brunoprietog** [comment]
Pressing alt + tab doesn't fix it in this case. I do feel it's a big problem, because lately NVDA is crashing quite a bit and restarting it is quite common. It's not nice to restart the browser all the time. But I'm pretty sure this is not a MathCat problem

**Comment by NSoiffer** [comment]
Apologies for the slow response. This slipped off my radar.

I occasionally have problems with NVDA not reading a page. I mostly use NVDA to test pages with math in them and have seen it happen in those pages maybe 1 out of 20 times (just a guess). I have seen it happen with other pages and have seen it happen in Firefox, Chrome, but not Edge. But not seeing it in Edge is because I rarely use Edge. When I tried it just now (several times), Edge/NVDA/MathCAT worked as expected.

As mentioned by @andrew-l-d, most of the times the solution seems to be to move the focus away and then back again, possibly reloading the page. However, there are times I needed to restart NVDA. I haven't ever been able to reliably replicate the problem, so I haven't reported it.

@brunoprietog: if you see this problem as independent of MathCAT, please close the issue. Otherwise, can you try to find a scenario where the problem happens most of the time? Potentially, the language/voice might be a part of the problem, so please include not only the MathCAT language settings, but also the NVDA speech settings.

**Comment by brunoprietog** [comment]
Don't worry, I'm pretty sure this is a NVDA problem and not a MathCat problem. I'll close it for now, unless I find some indication that MathCat is related to this. Thanks!
